CREATE OR REPLACE DATABASE CUSTOMER_DB;
USE DATABASE CUSTOMER_DB;

-- Tables
CREATE OR REPLACE TABLE CUSTOMERS (
    ID INT AUTOINCREMENT PRIMARY KEY,
    NAME STRING,
    EMAIL STRING,
    ADDRESS STRING,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE OR REPLACE TABLE PRODUCTS (
    PRODUCT_ID INT AUTOINCREMENT PRIMARY KEY,
    NAME STRING,
    CATEGORY STRING,
    PRICE FLOAT
);

CREATE OR REPLACE TABLE ORDERS (
    ORDER_ID INT AUTOINCREMENT PRIMARY KEY,
    CUSTOMER_ID INT,
    PRODUCT_ID INT,
    ORDER_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    QUANTITY INT DEFAULT 1,
    TOTAL_PRICE FLOAT,
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(ID),
    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS(PRODUCT_ID)
);