CREATE OR REPLACE DATABASE CUSTOMER_DB;
USE DATABASE CUSTOMER_DB;

-- Tables
CREATE OR REPLACE TABLE CUSTOMERS (
    ID INT AUTOINCREMENT PRIMARY KEY,
    NAME STRING NOT NULL,
    EMAIL STRING NOT NULL,
    ADDRESS STRING,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE OR REPLACE TABLE PRODUCTS (
    PRODUCT_ID INT AUTOINCREMENT PRIMARY KEY,
    NAME STRING NOT NULL,
    TICKER STRING NOT NULL,
    EXCHANGE STRING NOT NULL,
    PRICE FLOAT NOT NULL
);

CREATE OR REPLACE TABLE ORDERS (
    ORDER_ID INT AUTOINCREMENT PRIMARY KEY,
    CUSTOMER_ID INT NOT NULL,
    PRODUCT_ID INT NOT NULL,
    ORDER_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    QUANTITY INT DEFAULT 1 NOT NULL,
    TOTAL_PRICE FLOAT NOT NULL,
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(ID) ON DELETE CASCADE,
    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS(PRODUCT_ID) ON DELETE CASCADE
);